In [2]:
import numpy as np

### Matrix Diagonalization

$$
\boxed{A = PDP^{-1}}
$$

| Component | Description |
|-----------|-------------|
| **$A$** | Original square matrix |
| **$P$** | Matrix whose columns are the eigenvectors of $A$ |
| **$D$** | Diagonal matrix with eigenvalues of $A$ on the diagonal |
| **$P^{-1}$** | Inverse of $P$ |

#### Key Properties

- $A$ is **diagonalizable** if it has $n$ linearly independent eigenvectors
- The diagonal entries of $D$ are the **eigenvalues** of $A$
- The columns of $P$ are the corresponding **eigenvectors**

#### Example

$$
A = \begin{bmatrix} 4 & 1 \\ 2 & 3 \end{bmatrix}
$$

**Eigenvalues:**

$$
\lambda_1 = 5, \quad \lambda_2 = 2
$$

**Eigenvectors (columns of $P$):**

$$
v_1 = \begin{bmatrix} 0.70710678 \\ 0.70710678 \end{bmatrix}, \quad
v_2 = \begin{bmatrix} -0.4472136 \\ 0.89442719 \end{bmatrix}
$$

**Matrix $P$ (eigenvectors as columns):**

$$
P = \begin{bmatrix} 0.70710678 & -0.4472136 \\ 0.70710678 & 0.89442719 \end{bmatrix}
$$

**Matrix $D$ (eigenvalues on diagonal):**

$$
D = \begin{bmatrix} 5 & 0 \\ 0 & 2 \end{bmatrix}
$$

**Matrix $P^{-1}$ (inverse of $P$):**

$$
P^{-1} = \begin{bmatrix} 1.41421356 & 0.70710678 \\ -1.11803399 & 1.11803399 \end{bmatrix}
$$

**Verify $A = PDP^{-1}$:**

$$
A = \begin{bmatrix} 0.70710678 & -0.4472136 \\ 0.70710678 & 0.89442719 \end{bmatrix}
\begin{bmatrix} 5 & 0 \\ 0 & 2 \end{bmatrix}
\begin{bmatrix} 1.41421356 & 0.70710678 \\ -1.11803399 & 1.11803399 \end{bmatrix}
$$


In [9]:
# 1. matrix
A = np.array([[4, 1],
              [2, 3]])

print("Original Matrix A:")
print(A)
print("-" * 30)

# 2. Eigenvalue Decomposition (Diagonalization)
# numpy returns: eigenvalues, eigenvector matrix, and the inverse is calculated on the fly
eigenvalues, P = np.linalg.eig(A)

# 'eigenvalues' is an array, but we need a diagonal matrix D
D = np.diag(eigenvalues)

print("Eigenvalues (scaling factors):", eigenvalues)
print("\nEigenvector Matrix P (columns are eigenvectors):")
print(P)
print("\nDiagonal Matrix D (eigenvalues on the diagonal):")
print(D)
print("-" * 30)

# 3. Verify the formula: A = P * D * P^(-1)
P_inv = np.linalg.inv(P)
A_reconstructed = P @ D @ P_inv  # '@' is matrix multiplication in Python

print("A = (P * D * P^(-1)):")
print(A_reconstructed)
print("-" * 30)

# 4. THE MAGIC: See how easy it is to raise A to the 5th power using diagonalization!
A_power_5_normal = np.linalg.matrix_power(A, 5)

# Using diagonalization: A^5 = P * D^5 * P^(-1)
D_power_5 = np.diag(eigenvalues ** 5)  # Just raise the eigenvalues!
A_power_5_diag = P @ D_power_5 @ P_inv

print("A^5 calculated the normal (hard) way:")
print(A_power_5_normal)
print("\nA^5 calculated via diagonalization (P * D^5 * P^(-1)):")
print(A_power_5_diag)

Original Matrix A:
[[4 1]
 [2 3]]
------------------------------
Eigenvalues (scaling factors): [5. 2.]

Eigenvector Matrix P (columns are eigenvectors):
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]

Diagonal Matrix D (eigenvalues on the diagonal):
[[5. 0.]
 [0. 2.]]
------------------------------
A = (P * D * P^(-1)):
[[4. 1.]
 [2. 3.]]
------------------------------
A^5 calculated the normal (hard) way:
[[2094 1031]
 [2062 1063]]

A^5 calculated via diagonalization (P * D^5 * P^(-1)):
[[2094. 1031.]
 [2062. 1063.]]
