In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [22]:
#---------------
# load data
#---------------
iris = load_iris()
X, y = iris.data, iris.target

#---------------
# data split
#---------------
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # 42 is mostly used as seed!

#---------------
# data model (train)
#---------------
knn = KNeighborsClassifier(n_neighbors=3, n_jobs=-1)
knn.fit(X_train, y_train)

#---------------
# predict (test)
#---------------
y_pred = knn.predict(X_test)

#---------------
# evaluation
#---------------
accuracy = accuracy_score(y_test, y_pred)
cr = classification_report(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f'accuracy: {accuracy:.2%}')
print('='*50)
print(f'classification report: \n{cr}')
print('='*50)
print(f'confusion matrix: \n{cm}')

accuracy: 100.00%
classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion matrix: 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
